spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=olympics;encrypt=false
spring.datasource.username=SA
spring.datasource.password=Admin1234@
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/Olympics
spring.security.oauth2.client.registration.keycloak.client-id=olympics-app
spring.security.oauth2.client.registration.keycloak.client-secret=zImVjtvTAt3d8iU51ee6Ha1ZNQhXcpEW
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/keycloak
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8180/realms/Olympics
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username

keycloak.admin.client-secret=zImVjtvTAt3d8iU51ee6Ha1ZNQhXcpEW
keycloak.admin.client-id=olympics-app
keycloak.admin.realm=Olympics
keycloak.admin.server-url=http://localhost:8180